export const POKEMONS_HAS_ERRORED = 'POKEMONS_HAS_ERRORED';
export const POKEMONS_IS_LOADING = 'POKEMONS_IS_LOADING';
export const POKEMONS_FETCH_DATA_SUCCESS = 'POKEMONS_FETCH_DATA_SUCCESS';

export const POKEMON_HAS_ERRORED = 'POKEMON_HAS_ERRORED';
export const POKEMON_IS_LOADING = 'POKEMON_IS_LOADING';
export const POKEMON_FETCH_DATA_SUCCESS = 'POKEMON_FETCH_DATA_SUCCESS';
export const CLEAR_SELECTED_POKEMON = 'CLEAR_SELECTED_POKEMON';

export const CATCHED_POKEMONS_FETCH_DATA_SUCCESS =
  'CATCHED_POKEMONS_FETCH_DATA_SUCCESS';

export const CLEAR_ALL_POKEMONS = 'CLEAR_ALL_POKEMONS';
export const CLEAR_CATCHED_POKEMONS = 'CLEAR_CATCHED_POKEMONS';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ALL_POKEMONS_FETCHED = 'ALL_POKEMONS_FETCHED';
