export const ActionTypes = {
    SET_POKEMONS: 'SET_POKEMONS',
    SET_PAGE: 'SET_PAGE',
    APPEND_POKEMONS: 'APPEND_POKEMONS',
    SELECTED_POKEMON: 'SELECTED_POKEMON',
    REMOVE_SELECTED_POKEMON: 'REMOVE_SELECTED_POKEMON',
    CATCH_POKEMON: 'CATCH_POKEMON',
    CAUGHT_POKEMONS: 'CAUGHT_POKEMONS',
    RELEASE_POKEMON: 'RELEASE_POKEMON'
};